version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: horizon
      POSTGRES_USER: horizon
      POSTGRES_PASSWORD: 123UsedForTestOnly
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    image: mtsrus/horizon-backend:latest
    restart: unless-stopped
    environment:
      HORIZON__DATABASE__URL: postgresql+asyncpg://horizon:123UsedForTestOnly@db:5432/horizon
      HORIZON__AUTH__ACCESS_TOKEN__SECRET_KEY: 234UsedForTestOnly
      HORIZON__AUTH__PROVIDER: horizon.backend.providers.auth.dummy.DummyAuthProvider
      HORIZON__SERVER__LOGGING__PRESET: colored
      HORIZON__SERVER__DEBUG: 'false'
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8000/monitoring/ping
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
